import { BackendProfile } from './store';

export const mockProfiles: BackendProfile[] = [
  {
    id: '1',
    name: 'Alex',
    age: 28,
    lookingFor: 'serious',
    communicationStyle: 'balanced',
    conflictHandling: 'talk-immediately',
    corePriority: 'trust',
    nonNegotiable: 'Honesty in all situations',
    bio: 'Software engineer who values deep conversations and meaningful connections.',
  },
  {
    id: '2',
    name: 'Jordan',
    age: 31,
    lookingFor: 'serious',
    communicationStyle: 'text-a-lot',
    conflictHandling: 'take-time',
    corePriority: 'growth',
    nonNegotiable: 'Personal space and independence',
    bio: 'Entrepreneur focused on continuous self-improvement and mutual support.',
  },
  {
    id: '3',
    name: 'Sam',
    age: 26,
    lookingFor: 'casual',
    communicationStyle: 'only-when-needed',
    conflictHandling: 'avoid',
    corePriority: 'fun',
    nonNegotiable: 'No drama or negativity',
    bio: 'Creative professional who enjoys spontaneous adventures and lighthearted connections.',
  },
  {
    id: '4',
    name: 'Morgan',
    age: 34,
    lookingFor: 'serious',
    communicationStyle: 'balanced',
    conflictHandling: 'talk-immediately',
    corePriority: 'stability',
    nonNegotiable: 'Financial responsibility',
    bio: 'Project manager seeking a partner who values consistency and long-term planning.',
  },
  {
    id: '5',
    name: 'Casey',
    age: 29,
    lookingFor: 'not-sure',
    communicationStyle: 'text-a-lot',
    conflictHandling: 'take-time',
    corePriority: 'trust',
    nonNegotiable: 'Emotional availability',
    bio: 'Teacher who believes in open communication and building trust over time.',
  },
  {
    id: '6',
    name: 'Riley',
    age: 27,
    lookingFor: 'casual',
    communicationStyle: 'balanced',
    conflictHandling: 'talk-immediately',
    corePriority: 'fun',
    nonNegotiable: 'Sense of humor',
    bio: 'Marketing specialist who loves trying new restaurants and weekend getaways.',
  },
  {
    id: '7',
    name: 'Taylor',
    age: 32,
    lookingFor: 'serious',
    communicationStyle: 'only-when-needed',
    conflictHandling: 'take-time',
    corePriority: 'growth',
    nonNegotiable: 'Ambition and drive',
    bio: 'Architect with a passion for learning and supporting others in their goals.',
  },
  {
    id: '8',
    name: 'Quinn',
    age: 30,
    lookingFor: 'serious',
    communicationStyle: 'text-a-lot',
    conflictHandling: 'talk-immediately',
    corePriority: 'trust',
    nonNegotiable: 'Loyalty and commitment',
    bio: 'Healthcare professional who prioritizes open dialogue and mutual respect.',
  },
  {
    id: '9',
    name: 'Avery',
    age: 25,
    lookingFor: 'not-sure',
    communicationStyle: 'balanced',
    conflictHandling: 'avoid',
    corePriority: 'stability',
    nonNegotiable: 'Patience and understanding',
    bio: 'Graduate student exploring what meaningful connection looks like.',
  },
  {
    id: '10',
    name: 'Drew',
    age: 33,
    lookingFor: 'serious',
    communicationStyle: 'balanced',
    conflictHandling: 'take-time',
    corePriority: 'growth',
    nonNegotiable: 'Intellectual curiosity',
    bio: 'Data scientist who values thoughtful discussions and shared growth.',
  },
];
